# Generated by Django 2.0.5 on 2018-05-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='api.Classes'),
            preserve_default=False,
        ),
    ]
