# Generated by Django 2.0.5 on 2018-06-09 21:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='photo',
            field=models.ImageField(default=1, storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
            preserve_default=False,
        ),
    ]
