# Generated by Django 2.0.5 on 2018-06-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180609_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.AlterField(
            model_name='file',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
